server:
  port: 9000

spring:
  datasource:
    url: jdbc:oracle:thin:@211.38.173.250:1521:xe
    username: Hotel
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
  messages:
    basename: messages
   
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml

